# Copyright (C) 2022 Matthew T. Bucknall
#
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
# SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR
# IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 
function(avrdude ELF_FILE AVRD_DONGLE AVRD_INTERFACE AVRD_TARGET E_FUSE H_FUSE L_FUSE)

set(INPUT_FILE "${ELF_FILE}")
set(OUTPUT_FILE "${CMAKE_CURRENT_BINARY_DIR}/${ELF_FILE}.bin")
set(AVRDUDE "avrdude")
set(AVRDUDE_FLAGS -c ${AVRD_DONGLE} -P ${AVRD_INTERFACE} -p ${AVRD_TARGET} -F noreset)

add_custom_command(TARGET "${INPUT_FILE}" COMMAND "${CMAKE_SIZE}" -B "${INPUT_FILE}")

add_custom_target(reset COMMAND "${AVRDUDE}" ${AVRDUDE_FLAGS})
add_custom_target(erase COMMAND "${AVRDUDE}" ${AVRDUDE_FLAGS} -e)
add_custom_target(program DEPENDS "${INPUT_FILE}" COMMAND "${AVRDUDE}" ${AVRDUDE_FLAGS} -u -U flash:w:"${INPUT_FILE}")
add_custom_target(program_fuses COMMAND "${AVRDUDE}" ${AVRDUDE_FLAGS} -U efuse:w:${E_FUSE}:m -U hfuse:w:${H_FUSE}:m -U lfuse:w:${L_FUSE}:m)
endfunction()
